### ISSUE TITLE
Add progression events

### ISSUE THREAD

**Issue by Tzelon** [Dezeiraud/bsdiff-nodejs#2]
Hey,
Thanks for your work on this project.
I wonder how I can add an event to show how much time left to the end of the process.

Thanks 
Tzelon

**Comment by Brouilles** [comment]
Hello,
Currently this is not possible. But this is a good idea, probably for a future version.

Thanks

**Comment by Tzelon** [comment]
Is that demand tinkering with the C code?

**Comment by Brouilles** [comment]
For a real data yes.

**Comment by Tzelon** [comment]
Thanks.
I'm hoping to see that implemented in the near version :)

**Comment by Brouilles** [comment]
Work In Progress 133610050f35e7f8446d238a9b179acd6e1772b8

**Comment by Brouilles** [comment]
Now available with the version 2.0.0 

- Better performance
- Async
- Get percentage with callback
