### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by annakocheshkova** [Dezeiraud/bsdiff-nodejs#5]
**Describe the bug**
Npm is unable to install the library.

**To Reproduce**
`npm install --save bsdiff-nodejs`

**Expected behavior**
Library is installed.

**Screenshots**
![image](https://user-images.githubusercontent.com/34677812/43308827-79fc47a4-918b-11e8-9701-183c534fac36.png)

**Desktop (please complete the following information):**
- OS: Windows/Mac (both)
- NodeJS version 8.11.1

**Comment by Brouilles** [comment]
Hello, 
Thanks for report the issue. 
We will study the problem, I'll get back to you quickly.

**Comment by Brouilles** [comment]
We have a temporary fix, install another package before bsdiff-nodejs works

**Comment by Brouilles** [comment]
Fix 9b0e97ad543cb99bc9da6dc1c5748b9982e21813 - bsdiff-nodejs 2.0.1

**Comment by annakocheshkova** [comment]
Hi guys, that helped, but unfortunately there is another error. I would appreciate your help because I really want to use this module! I filled the issue.
